import { Property } from './types';

export const properties: Property[] = [
    {
        id: 1,
        title: 'Cobertura Duplex',
        type: 'Apartamento',
        category: 'Venda',
        location: 'Jardins',
        bedrooms: 4,
        parking: 3,
        area: 320,
        price: 3450000,
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1974&auto=format&fit=crop',
        badge: 'Lançamento',
        isFeatured: true
    },
    {
        id: 2,
        title: 'Apartamento Alto Padrão',
        type: 'Apartamento',
        category: 'Venda',
        location: 'Moema',
        bedrooms: 3,
        parking: 2,
        area: 180,
        price: 1250000,
        image: '/src/assets/images/apartamento_moema_1779039410989.png',
        isFeatured: true
    },
    {
        id: 3,
        title: 'Casa Contemporânea',
        type: 'Casa',
        category: 'Venda',
        location: 'Alphaville',
        bedrooms: 5,
        parking: 4,
        area: 420,
        price: 1950000,
        image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80&w=1974&auto=format&fit=crop',
        badge: 'Oportunidade',
        isFeatured: true
    },
    {
        id: 4,
        title: 'Apartamento 2 Dorm',
        type: 'Apartamento',
        category: 'Aluguel',
        location: 'Pinheiros',
        bedrooms: 2,
        parking: 1,
        area: 75,
        price: 3200,
        condoPrice: 800,
        image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1974&auto=format&fit=crop',
        badge: 'Pet Friendly'
    },
    {
        id: 5,
        title: 'Cobertura Mobiliada',
        type: 'Apartamento',
        category: 'Aluguel',
        location: 'Itaim Bibi',
        bedrooms: 3,
        parking: 2,
        area: 160,
        price: 7500,
        condoPrice: 1200,
        image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1974&auto=format&fit=crop',
        badge: 'Mobiliado'
    },
    {
        id: 6,
        title: 'Studio Investimento',
        type: 'Apartamento',
        category: 'Venda',
        location: 'Faria Lima',
        bedrooms: 1,
        parking: 1,
        area: 42,
        price: 480000,
        image: 'https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80&w=1974&auto=format&fit=crop'
    },
    {
        id: 7,
        title: 'Casa com Quintal',
        type: 'Casa',
        category: 'Aluguel',
        location: 'Saúde',
        bedrooms: 3,
        parking: 2,
        area: 140,
        price: 4500,
        condoPrice: 0,
        image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=1974&auto=format&fit=crop'
    },
    {
        id: 8,
        title: 'Sala Comercial',
        type: 'Comercial',
        category: 'Venda',
        location: 'Brooklin',
        bedrooms: 0,
        parking: 3,
        area: 180,
        price: 1450000,
        image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1974&auto=format&fit=crop',
        badge: 'Financiável'
    },
    {
        id: 9,
        title: 'Mansão de Luxo',
        type: 'Casa',
        category: 'Venda',
        location: 'Morumbi',
        bedrooms: 6,
        parking: 8,
        area: 850,
        price: 12500000,
        image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1974&auto=format&fit=crop',
        badge: 'Exclusivo'
    }
];